### ISSUE TITLE
ERROR PermissionError: [WinError 5] Access is denied?

### ISSUE THREAD

**Issue by TAnvilrock** [Chamepp/GoogleForms#11]
```
Welcome To GoogleForms Hack
Version 1.0.0
Developed By Ashkan Ebtekari
2020 @ Copyright



[?] What Type Of Attack You Want To Perform ? (Use arrow keys)
Starting Rapid Input Attack ...
Started the Rapid Operation ...

[*] After Entering The Path We Will Save The Data !
[*] You Can Download Chrome Driver From https://chromedriver.chromium.org/downloads
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ADMIN\OneDrive\Desktop\GoogleForms-master\App\main.py", line 14, in <module>
    class Main:
  File "C:\Users\ADMIN\OneDrive\Desktop\GoogleForms-master\App\main.py", line 37, in Main
    rapidattack = rapid.getrapid()
  File "C:\Users\ADMIN\OneDrive\Desktop\GoogleForms-master\App\rapid.py", line 63, in getrapid
    driver = webdriver.Chrome(executable_path=chromedriver, chrome_options=chromeOptions)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'webdrivers' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

**Comment by Chamepp** [comment]
Check for your system permissions on dependencies.json
