### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by Brian040101** [Chamepp/GoogleForms#13]
|================|
                 | I Hate         |
 ===========     |        Robots! |     ========
 ===========    /|================|     ==
 ===           /               =        ==                    ===
 ===          /                =        =====                 =
 ===    =====   ==== ==== ==== = ====   =====  ==== = = =     ===
 =====     ==   =  = =  = =  = = ==     ==     =  = ==  =====   =
 ============   ==== ==== ==== = ====   ==     ==== =   = = = ===
                             =
                          ====

Welcome To GoogleForms Hack
Version 1.0.0
Developed By Ashkan Ebtekari
2020 @ Copyright

[?] What Type Of Attack You Want To Perform ? (Use arrow keys)
Starting Rapid Input Attack ...
Started the Rapid Operation ...

[*] After Entering The Path We Will Save The Data !
[*] You Can Download Chrome Driver From https://chromedriver.chromium.org/downloads
[~] Please Enter Your Driver Path : /usr/lib/chromium-browser/chromedriver
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    class Main:
  File "main.py", line 37, in Main
    rapidattack = rapid.getrapid()
  File "/home/pi/GoogleForms/App/rapid.py", line 63, in getrapid
    driver = webdriver.Chrome(executable_path=chromedriver, chrome_options=chromeOptions)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Driver info: chromedriver=2.35 (0),platform=Linux 5.10.17-v7+ armv7l)

What is this problem?

**Comment by Chamepp** [comment]
The problem is with your webdriver.
Make sure to use main for chrome and match the driver version and your browser.
