### ISSUE TITLE
referenced before assignment

### ISSUE THREAD

**Issue by X-KERING** [Chamepp/GoogleForms#18]
### HELP ME!!
[?] Which One Is Your Target ? 

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    class Main:
  File "main.py", line 39, in Main
    rapidattack = rapid.getrapid()
  File "/home/dell/GoogleForms-master/App/rapid.py", line 99, in getrapid
    usertarget = input("\nEnter Your Target [1 TO {max}] : ".format(max = convertcount))
UnboundLocalError: local variable 'convertcount' referenced before assignment

**Comment by Chamepp** [comment]
have you declared form url correctly ?
potentially it wasnt able to scan checkboxes
make sure your form contain checkboxes or radio buttons
