### ISSUE TITLE
[WinError 5] Access is denied despite running cmd as administrator

### ISSUE THREAD

**Issue by ahmadrr** [Chamepp/GoogleForms#26]
main

                 |================|
                 | I Hate         |
 ===========     |        Robots! |     ========
 ===========    /|================|     ==
 ===           /               =        ==                    ===
 ===          /                =        =====                 =
 ===    =====   ==== ==== ==== = ====   =====  ==== = = =     ===
 =====     ==   =  = =  = =  = = ==     ==     =  = ==  =====   =
 ============   ==== ==== ==== = ====   ==     ==== =   = = = ===
                             =
                          ====

Welcome To GoogleForms Hack
Version 1.0.0
Developed By Ashkan Ebtekari
2020 @ Copyright

[?] What Type Of Attack You Want To Perform ? (Use arrow keys)
Starting Secret Finder Attack ...
freebirdFormviewerComponentsQuestionBaseTitle
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Downloads\Programs\GoogleForms\main.py", line 15, in <module>
    class Main:
  File "D:\Downloads\Programs\GoogleForms\main.py", line 43, in Main
    secretfinder = answer.getanswer()
  File "D:\Downloads\Programs\GoogleForms\answer.py", line 56, in getanswer
    driver = webdriver.Chrome(executable_path=chromedriver, chrome_options=chromeOptions)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'GoogleForms' executable may have wrong permissions. Please see https://chromedriver.chromium.org/home

**Comment by girik8040** [comment]
ahh yea this is the problem with windows. just use linux it works fine for me
