### ISSUE TITLE
ive encountered this while installing one of the packages required to run this, can you pls help me?

### ISSUE THREAD

**Issue by Zagreeyeet** [Chamepp/GoogleForms#28]
Collecting selectmenu
  Using cached SelectMenu-1.0.0b2.tar.gz (3.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ggup0\AppData\Local\Temp\pip-install-6y4w6r1v\selectmenu_5e17682c046349f7be209dbe0f438422\setup.py", line 5, in <module>
          from selectmenu import __author__, __version__
        File "C:\Users\ggup0\AppData\Local\Temp\pip-install-6y4w6r1v\selectmenu_5e17682c046349f7be209dbe0f438422\selectmenu\__init__.py", line 4, in <module>
          from selectmenu.core import SelectMenu
        File "C:\Users\ggup0\AppData\Local\Temp\pip-install-6y4w6r1v\selectmenu_5e17682c046349f7be209dbe0f438422\selectmenu\core.py", line 6, in <module>
          from prompt_toolkit.token import Token
      ImportError: cannot import name 'Token' from 'prompt_toolkit.token' (C:\Users\ggup0\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\token.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

i dont really have an any idea whats happening there and im just learning py currently self learning

**Comment by Zagreeyeet** [comment]
> Collecting selectmenu Using cached SelectMenu-1.0.0b2.tar.gz (3.4 kB) Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [10 lines of output] Traceback (most recent call last): File "", line 2, in File "", line 34, in File "C:\Users\ggup0\AppData\Local\Temp\pip-install-6y4w6r1v\selectmenu_5e17682c046349f7be209dbe0f438422\setup.py", line 5, in from selectmenu import **author**, **version** File "C:\Users\ggup0\AppData\Local\Temp\pip-install-6y4w6r1v\selectmenu_5e17682c046349f7be209dbe0f438422\selectmenu__init__.py", line 4, in from selectmenu.core import SelectMenu File "C:\Users\ggup0\AppData\Local\Temp\pip-install-6y4w6r1v\selectmenu_5e17682c046349f7be209dbe0f438422\selectmenu\core.py", line 6, in from prompt_toolkit.token import Token ImportError: cannot import name 'Token' from 'prompt_toolkit.token' (C:\Users\ggup0\AppData\Local\Programs\Python\Python310\lib\site-packages\prompt_toolkit\token.py) [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.
> 
> i dont really have an any idea whats happening there and im just learning py currently self learning
