### ISSUE TITLE
can you guys help me?

### ISSUE THREAD

**Issue by Zagreeyeet** [Chamepp/GoogleForms#30]
Traceback (most recent call last):
  File "C:\Users\ggup0\Downloads\GoogleForms-master\GoogleForms-master\App\main.py", line 15, in <module>
    class Main:
  File "C:\Users\ggup0\Downloads\GoogleForms-master\GoogleForms-master\App\main.py", line 39, in Main
    rapidattack = rapid.getrapid()
  File "C:\Users\ggup0\Downloads\GoogleForms-master\GoogleForms-master\App\rapid.py", line 99, in getrapid
    usertarget = input("\nEnter Your Target [1 TO {max}] : ".format(max = convertcount))
UnboundLocalError: local variable 'convertcount' referenced before assignment

this always pop up whenever i start it

**Comment by Zagreeyeet** [comment]
help pls

**Comment by wrustem** [comment]
I think, that did nt work, because google form start use attack protection. Now we dont find in page "freebirdFormviewerComponentsQuestionRadioLabel", so this project dont work
